GET http://localhost:3001/api/notes 
###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
  "content": "Use lots of console.logs",
  "important": true,
  "userId": "6a3b041ba0dc85702bbfb059"
}

###
PUT http://localhost:3001/api/notes/6a29ed426fec0e880aacb012
Content-Type: application/json

{
  "content": "less", 
  "important": false
}


###
POST http://localhost:3001/api/users 
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "patched"
}