GET http://localhost:3001/api/persons 
###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
  "content": "REST is good in testing backend",
  "important": true
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada",
  "number" : "88"
}

###
DELETE http://localhost:3001/api/persons/6a2c316444630b1cee1d981f